---
name: CI Workflow

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  docker-publish:
    defaults:
      run:
        shell: bash

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          show-progress: false

      - name: Extract Docker Image Name
        id: image
        run: |
          echo "name=ghcr.io/${GITHUB_REPOSITORY,,}:latest" >>${GITHUB_OUTPUT}

      - name: Log into registry
        uses: docker/login-action@c99871dec2022cc055c062a10cc1a1310835ceb4 # v4.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: |
          docker buildx build \
            --no-cache \
            --pull \
            --tag ${{ steps.image.outputs.name }} \
            .

      - name: Docker Push
        run: |
          docker push ${{ steps.image.outputs.name }}
        if: ${{ github.ref == 'refs/heads/master' }}
